branch-defaults:
  master:
    environment: utgifterDev-env
global:
  application_name: utgifter-dev
  default_ec2_keyname: aws-eb-utgifter-dev
  default_platform: 64bit Amazon Linux 2016.03 v2.1.0 running Python 3.4
  default_region: eu-central-1
  profile: eb-cli
  sc: git
