# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-19 14:34
from __future__ import unicode_literals

import colorful.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('number', models.CharField(blank=True, max_length=200, verbose_name='Number (optional)')),
                ('color', colorful.fields.RGBColorField(default='#b9d8e7')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utgifter.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Matcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('method', models.CharField(choices=[('EXACT', 'Exact'), ('CONTAINS', 'Contains'), ('ICONTAINS', 'Contains (case-insensitive)'), ('FUZZY', 'Fuzzy')], default='ICONTAINS', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SearchString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(max_length=50)),
                ('matcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utgifter.Matcher')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', colorful.fields.RGBColorField(default='#b9d8e7')),
                ('name', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='matcher',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utgifter.Tag'),
        ),
        migrations.AddField(
            model_name='matcher',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='charge',
            name='matcher',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utgifter.Matcher'),
        ),
        migrations.AddField(
            model_name='charge',
            name='tag',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utgifter.Tag'),
        ),
        migrations.AddField(
            model_name='charge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
