# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-23 01:02
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import User

def create_superuser(apps, schema_editor):
    u = User.objects.create_user(username="su",
                                 email="a@a.com",
                                 password="qwerasdf",
                                 is_superuser=True,
                                 is_staff=True)
    u.save()

    u = User.objects.create_user(username="user1",
                                 email="b@b.com",
                                 password="qwerasdf",
                                 is_superuser=False,
                                 is_staff=False)
    u.save()

class Migration(migrations.Migration):
    dependencies = [
        ('utgifter', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
