# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-27 19:25
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('utgifter', '0002_auto_20160423_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorful.fields.RGBColorField(default='#b9d8e7'),
        ),
    ]
