# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-20 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utgifter', '0002_auto_20161119_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='comment',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
